#To explore data, you can  
#identify observations in plots  
#-brush observations in linked scatter plots, histograms, box plots, line plots,
#contour plots, and three-dimensional rotating plots  
#exclude observations from graphs and analyses  
#search, sort, and edit data  transform variables  
#color observations based on the value of a variable

#to make a simple plot
plot(x,y)

# For data manipulation and tidying
library(dplyr)

# For data visualizations
library(ggplot2)

# For modeling and predictions
library(caret)
library(glmnet)
library(ranger)
library(e1071)

# For Data Cleaning
library(tidyverse)
library(rlang)
library(stringr)
library("janitor")

#Janitor function
#to turn column names to lowercase and use _ as seperator
clean_names(data)
janitor::clean_names(data)
#to remove any columns that are entirely empty and entire rows that are entirely empty
remove_empty(data, which = c("rows","cols"))



#for more on janitor
"https://garthtarr.github.io/meatR/janitor.html#catalog_of_janitor_functions"

#check for duplicates
sum(duplicated(dataset))

#check for missing variables
colSums(sapply((data), is.na))

#install the 'tidyverse' package and run it
#take the mean of the data
mean()
summary()

#structure of data and looking at data
str()
head()
glimpse()
dim()

#how many columns and how many rows
ncol(data)
nrow(data)

#handling missing variables
is.na(data) #check if its missing
na.omit(data) #remove rows with na from the list
complete.cases(data) #returns vector of rows with na values e.g
data[complete.cases(data)]


#dealing with string and text
#install.packages("stringi")


na.rm
mean(, na.rm = TRUE)
  head(
    
    colSums(is.na(
      
#calculate variance
      #To insert a pipe %>%, use the keyboard shortcut Ctrl+Shift+M
      
data() # lists all the datasets in all the packages in memory
data(package="datasets") # lists all the datasets in the "datasets" package
data(Orange) # loads the orange dataset in memory
?Orange # Help for the "Orange" Datasets
str_data("datasets") # gives the structure of all the datasets in the datasets package.
      
#getting working directory
getwd()

#manually set your working directory using setwd("a path on your computer")



#examinig distribution of variables, categorical variables

#turning data into a tibble:
as_tibble()


read_csv("The first line of metadata
  The second line of metadata
  x,y,z
  1,2,3", skip = 2)


# Helper function, Creating a helper function that will take an input string and 
#convert it to variable for boxplot

Iris_plot <- function(df=iris, y) {
  ggplot(df, aes(x = Species, y = !! sym(y) )) + 
    geom_boxplot(notch = TRUE) +
    theme_classic(base_size = 10)
}

#Chunk Options for r markdown
Chunk output can be customized with knitr options, arguments set in the {} of a chunk header. Above, we use five arguments:
  
  include = FALSE #prevents code and results from appearing in the finished file. R Markdown still runs the code in the chunk, and the results can be used by other chunks.
echo = FALSE #prevents code, but not the results from appearing in the finished file. This is a useful way to embed figures.
message = FALSE #prevents messages that are generated by code from appearing in the finished file.
warning = FALSE #prevents warnings that are generated by code from appearing in the finished.
fig.cap = "..." adds a caption to graphical results.

page(lm)



# if some of the column names have spaces in them. This line changes the column names to 
# versions without spaces, which let's us talk about the columns by their names.
names(chocolateData) <- make.names(names(chocolateData), unique=TRUE)


#creating a summary stat table

# Summary Statistics
cols <- numerics %>% select(debt, rent_mean, female_age_mean) %>% 
  filter(!is.na(debt), !is.na(rent_mean), !is.na(female_age_mean))

do.call(cbind, lapply(cols, summary))

#USE vTABLE for summary stats
#install.packages("vtable")
library(vtable)